name: paint
description: An image editor in your browser
version: 0.0.1
author: Michael Richter

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  angular: ^5.0.0-alpha
  js: ^0.6.1

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
