name: paint
description: A image editor in your browser
version: 0.0.1
author: Michael Richter

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  angular: ^5.0.0-alpha
  #angular_components: ^0.8.0
  js: ^0.6.1
  #js_proxy: "^0.1.4"

dev_dependencies:
##  angular_test: ^1.0.0
#  browser: ^0.10.0
#  dart_to_js_script_rewriter: ^1.0.1
##  test: ^0.12.0
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0

#transformers:
#- angular:
#    entry_points:
#    - web/main.dart
##    - test/**_test.dart
##- test/pub_serve:
##    $include: test/**_test.dart
#- dart_to_js_script_rewriter
#- $dart2js:
#    commandLineOptions: [--enable-experimental-mirrors]

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
